# Generated by Django 5.2.6 on 2025-10-01 04:02

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dermal.profile')),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvoted_posts', to='Dermal.profile')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_posts', to='Dermal.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Dermal_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('drug_history', models.TextField(blank=True, null=True)),
                ('illness_history', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('heatmap', models.TextField(blank=True, null=True)),
                ('more_predict', models.TextField(blank=True, null=True)),
                ('symptom', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('explain', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dermal.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Dermal.post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dermal.profile')),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvoted_comments', to='Dermal.profile')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_comments', to='Dermal.profile')),
            ],
        ),
    ]
