# Generated by Django 5.2.6 on 2025-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dermal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dermal_image',
            name='heatmap',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
