# Generated by Django 5.2.6 on 2025-10-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dermal', '0003_alter_dermal_image_heatmap_alter_dermal_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dermal_image',
            name='heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/'),
        ),
        migrations.AlterField(
            model_name='dermal_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dermal_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
