# Generated by Django 5.2.6 on 2026-01-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dermal', '0004_alter_dermal_image_heatmap_alter_dermal_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dermal_image',
            name='drug_history_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dermal_image',
            name='illness_history_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dermal_image',
            name='symptom_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
